package exceptions_demo;

public class Exceptions {

	public static void main(String[] args) {

		int a=10;
		int b=0;
		int res=0;
		
		try{	//try catch block as follows.
		res = a/b;
		System.out.println("Result is "+res);
		}catch(ArithmeticException e){
			System.out.println("Cannot divide by 0.");
		}finally{	//not necessary, but, must come last.
			System.out.println("Result is "+res);
		}
		
		System.out.println("This is other lines of code in my app.");

	}

}
